version: "3.3"
services:
    postgres:
        container_name: easytech-postgres
        restart: always
        image: postgres  
        networks:
            - modulocker        
        ports:  
            - "5432:5432"
        volumes:
            - ./volumes/postgres:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: Postgres2021!
            POSTGRES_DB: ews001
            DB_EXTENSION: uuid-ossp

    pgadmin:
        container_name: easytech-pgadmin
        restart: always
        image: dpage/pgadmin4
        networks:
            - modulocker
        ports: 
            - "15432:80"            
        environment: 
            PGADMIN_DEFAULT_EMAIL: "marcos.aquino@easytech.com.br"
            PGADMIN_DEFAULT_PASSWORD:   "PgAdmin2021!"    
        depends_on: 
            - postgres
            
networks: 
    modulocker:
        driver: bridge